### ISSUE TITLE
Vacuum pump - Set point off by a factor of 4/3

### ISSUE THREAD

**Issue by juli4nb4dillo** [numat/ika#69]
I ran these tests against Denali:

```python
import asyncio
from ika.driver import Vacuum
from ika.driver import VacuumProtocol

def arun(awaitable):
    loop = asyncio.get_event_loop()
    return loop.run_until_complete(awaitable)

vac = Vacuum("192.168.10.9:26")

>>> arun(vac.set(100))
>>> arun(vac.get())
{'active': False, 'mode': 'MANUAL', 'pressure': {'setpoint': 99.77, 'actual': 735.48}}
# Displays 133 on the instrument
>>> arun(vac.set(200))
>>> arun(vac.get())
{'active': False, 'mode': 'MANUAL', 'pressure': {'setpoint': 199.55, 'actual': 735.33}}
# Displays 266 in the instrument
>>> arun(vac.set(250))
>>> arun(vac.get())
{'active': False, 'mode': 'MANUAL', 'pressure': {'setpoint': 249.81, 'actual': 735.33}}
# Displays 333 in the instrument
>>> arun(vac.set(300))
>>> arun(vac.get())
{'active': False, 'mode': 'MANUAL', 'pressure': {'setpoint': 299.32, 'actual': 735.48}}
# Displays 399 in the instrument
```

So there are two things:

1. The set point gets slightly off when read from the instrument from the driver.
2. The displayed set point (in the actual instrument) is off by a factor of `1.333`, roughly 3/4. So I'm assuming we have some small mistake encoding and decoding the setpoint when sending it to the instrument.

**Comment by juli4nb4dillo** [comment]
I traced it back to this piece of code:

https://github.com/numat/ika/blob/af21b9257228cdf846af417b28c0c2635fb94c1c/ika/driver.py#L483-L491

It assumes the data is displayed/received in mbar instead of mmHg, I'm removing that.

**Comment by juli4nb4dillo** [comment]
Funny story, the setpoint is in `mmHg`, but the raw reading is in `mbar`, so it's not consistent.

**Comment by alexrudd2** [comment]
This was an intentional decision to work in mmHg rather than mbar.  However, if Khantey prefers the other way that's fine :)


As this is a breaking change, it should become `0.5.0 not 0.4.1, though

**Comment by juli4nb4dillo** [comment]
All right, I can bump the version.
