### ISSUE TITLE
NameError, cannot get this to work

### ISSUE THREAD

**Issue by patrickdewitNL** [numat/ika#84]
In all fairness, I'm not a programmer but would identify more as a trained monkey who has a little clue about what he is doing. I am trying to get this to work but for some odd reason I cant even get the provided example to work and I have no clue where to start solving this. 

Running Python 3.10, COM3 shows up in my device manager.

```
import asyncio
from ika import Hotplate, OverheadStirrer

async def get():
    async with OverheadStirrer('COM3') as strirrer:
        print(await stirrer.get())


asyncio.run(get())
```

```
Traceback (most recent call last):
  File "xxxxx\ika-control-0.5.0\test.py", line 9, in <module>
    asyncio.run(get())
  File "c:\xxx\appdata\local\programs\python\python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "c:\xxx\appdata\local\programs\python\python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\xxx\ika-control-0.5.0\test.py", line 6, in get
    print(await stirrer.get())
NameError: name 'stirrer' is not defined
```

**Comment by alexrudd2** [comment]
Thanks for the report!  Apologies for not replying sooner; I have notifications turned off.

I hope you already found it, but there is a typo in the README.  Below is the fixed line.
```python
async with OverheadStirrer('COM3') as stirrer:  #  NOT STRIRRER
```

**Comment by alexrudd2** [comment]
> In all fairness, I'm not a programmer but would identify more as a trained monkey who has a little clue about what he is doing

Hey, that's how I _became_ a programmer :)
